### PR TITLE
onFilterTextChange event, you can bind to this to update datasrouce

### PR DESCRIPTION
**Pull request by mezzo9**
We needed to dynamically update the Data Source that the dropdown binds to. 
Added this simple event to achieve this.
Thought others might have a similar requirement.
Hope this help.
AFShin

### CODE REVIEW

**Comment by NileshPatel17** [comment]
Such use case would be rare. Appreciate if you can share your case.
I will merge this PR.

Thanks.
Nilesh Patel

**Comment by mezzo9** [comment]
Good Evening,

The reason I need that is our backend rest api (jira) that provides the
data source can only return 1000 record at a time, with this change I can
get use the filter to return only the data that starts with or contains
those characters.

I hope this makes sense.
Please let me know if you have any questions

Afshin

**Comment by NileshPatel17** [comment]
I was expecting the same use case. Just wanted to confirm.
Can we improve on this code?? on each keypress, it would make api call. How about using debounceTime and switchMap??

Please share your view.

Nilesh Patel

**Comment by mezzo9** [comment]
Good Morning Nilesh,

Sorry It took a while to get back to you.
At this time for what I needed, debounce doesn't make sense. I need with
every key stroke a new list to get fetched.

in 2 weeks I'll be working on optimizing the software that my team is
working on, and if anything changes will definitely keep you in the loop.

Thanks,

**Pull request merged**
