### PR TITLE
Add support for numbers

### PR DESCRIPTION
**Pull request by WWL-MikeRoberts**
Allow data items to be numbers instead of just strings or objects.

### CODE REVIEW

**Comment by NileshPatel17** [comment]
@WWL-MikeRoberts  Thanks!

**Comment by WWL-MikeRoberts** [comment]
You're welcome. Any chance you can deploy a new version to NPM?

**Comment by NileshPatel17** [comment]
I am thinking of keeping text as string only. id can be number or string but text would be always string. what do you think?

**Comment by WWL-MikeRoberts** [comment]
Nilesh,

That doesn't work for my use case. The text value is what populates the
ngModel so if you are providing a list of numbers as options then what you
expect to get back is a list of numbers, not a list of strings. It seems
much cleaner to me to allow both to be numbers. I do understand that the
word text could imply a string so I could see how the name of that property
may not be accurate with this change.

Thanks,


---
Mike Roberts
Founder and CTO
W.W.Lane L.L.C. <http://www.wwlane.com/>

**Comment by NileshPatel17** [comment]
alright. will keep it. added test cases for pipes as well. code was breaking due to your code changes. Please pull latest code. let me know if you find any issue.

**Comment by WWL-MikeRoberts** [comment]
Nilesh,

Looks good to me.

Thanks,

---
Mike Roberts
Founder and CTO
W.W.Lane L.L.C. <http://www.wwlane.com/>

**Comment by WWL-MikeRoberts** [comment]
Any update on getting a new version pushed to NPM? We are at the end of our project and have to make a decision of whether to use a fork or not.

**Comment by NileshPatel17** [comment]
Published new version 0.2.6.

**Comment by WWL-MikeRoberts** [comment]
Nilesh,

Thank you a bunch.

---
Mike Roberts
Founder and CTO
W.W.Lane L.L.C. <http://www.wwlane.com/>

**Pull request merged**
