### PR TITLE
Issue #182 fixed 'allow search filter input even when there is no dat…

### PR DESCRIPTION
**Pull request by sushil-suthar**
Issue #182 fixed 'allow search filter input even when there is no data in the dropdown list. so that someone can use it for server side search also.

### CODE REVIEW

**Comment by NileshPatel17** [comment]
please make use existing property ```allowSearchFilter```.

**Comment by NileshPatel17** [comment]
or shall we keep new property ```allowSearchFilterOnEmptyList'''. let me think

**Comment by sushil-suthar** [comment]
I think both are serving different purpose.
"allowSearchFilter" is to enable search filter
allowSearchFilterOnEmptyList is to enable above one on empty list.

**Comment by NileshPatel17** [comment]
As per my understanding, with ```allowSearchFilterOnEmptyList``` flag, user will type in search textbox, and it will make use of ```onFilterChange``` event to get data from api ,and on promise resolve data will be bind to the datasource.
html``` <ng-multiselect-dropdown name="city" [placeholder]="'Select City'" [data]="cities" onFilterChange)="onFilterChange($event)">
        </ng-multiselect-dropdown>
```

javascript```
onFilterChange(searchText: string) {
    this.http.getData.subscribe(data=> this.cities=data);
  }
```

Please correct me if i am wrong.

**Comment by sushil-suthar** [comment]
Yes you are right.

**Comment by NileshPatel17** [comment]
Alright.
1. ```onFilterChange``` emits data on each key press. can we use ```debounce```
2.   what if user wants to search remote data even if data list is not empty.
3.  Property name change: Does ```allowRemoteDataSearch``` make more sense than ```allowSearchFilterOnEmptyList ```
4. you missed out to  set default value(```multiselect.component.ts``` at line no 46)
5. can you write test cases for this feature. If you havn't written, no problem, i will write.

**Comment by sushil-suthar** [comment]
allowRemoteDataSearch should be fine.

I have less experiance in test cases. 😊

**Comment by sushil-suthar** [comment]
Hi nilesh,
Any update on merging.
We are waiting for the merge and new release. So that we can update the library in our application.

**Comment by NileshPatel17** [comment]
i am waiting to make following changes:-
1. rename property to ```allowRemoteDataSearch ```
2. set default value to false

Once, it is done, i will merge and publish new release.

**Comment by sushil-suthar** [comment]
I have renamed and set default value.

**Comment by dipaliwagh30** [comment]
> As per my understanding, with `allowSearchFilterOnEmptyList` flag, user will type in search textbox, and it will make use of `onFilterChange` event to get data from api ,and on promise resolve data will be bind to the datasource.
> 
> template code: <ng-multiselect-dropdown [data]="cities" onFilterChange)="onFilterChange($event)">
> 
> ```js
> onFilterChange(searchText: string) {
>     this.http.getData.subscribe(data=> this.cities=data);
>   }
> ```
> 
> Please correct me if i am wrong.

I'm not able to bind new data fetched from api on onFilterChange event. my requirement is, I want to bind 1st 100 records and if search string does not match with any record out of 100, I want to bind next 100 records from api. but this is not happening. please help me with this scenario.
template code:
<ng-multiselect-dropdown [data]="entity" (onFilterChange)="onFilterChange($event)">
onFilterChange(searchText: string) {
    this.http.getData(searchText).subscribe(data=> this.entity=data);
  }

**Pull request merged**
