### PR TITLE
fixed itemsShowLimit issue

### PR DESCRIPTION
**Pull request by c4rnot**
fixed itemsShowLimit issue and added it to the example.

The problem had been the flex attribute competing with the hidden attribute.  Solved by adding an extra layer of spans. flex in outer span, styling attributes in inner span.

### CODE REVIEW

**Comment by mrsants** [comment]
what is the reason for such delay in pull requests?

**Comment by walldiv** [comment]
@NileshPatel17  - please respond to the pull request .... this is going on several months now & the solution has been provided.

**Comment by NileshPatel17** [comment]
@walldiv can you please tell me what was the issue? I will merge this PR asap.
Sorry for the inconvenience.

**Comment by walldiv** [comment]
> @walldiv can you please tell me what was the issue? I will merge this PR asap. Sorry for the inconvenience.

The same issue as everyone in this issue tracked - itemsShowLimit doesnt work in angular - 12.2...  I set it to any number, and the full amount of SELECTED set shows up in the select box.

**Comment by NileshPatel17** [comment]
@walldiv ok.. will merge. Thanks for the contribution.

**Comment by NileshPatel17** [comment]
@walldiv new release published. please test with version 0.3.7.

**Comment by mrsants** [comment]
@NileshPatel17 you can close the issue 323 that managed the discussion

**Pull request merged**
